// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjgspbyckknhoetrifko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqZ3NwYnlja2tuaG9ldHJpZmtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NTE4MTAsImV4cCI6MjA2MjAyNzgxMH0.8FuEh6hHneLreY1eGI05QVMi_-8XnKtN7Hox9OOOM4w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);